### PR TITLE
Decaffeination

### PR DESCRIPTION
**Pull request by mserranom**
Project decaffeination.

`decaffeination.sh` log:
[decaf-log.txt](https://github.com/overleaf/spelling/files/3334602/decaf-log.txt)

### CODE REVIEW

**Comment by 40thieves** [comment]
I think the build system will need updating too. Just looking at it, I think the scripts in `package.json` and the `Makefile` need updating. But there's also stuff in `rakefile.rb`. I can't tell if that's used or not. Probably worth checking `Jenkinsfile` & `Dockerfile` too.

**Comment by mserranom** [comment]
this PR has some issues, closing

**Comment by das7pad** [comment]
> some issues

Would you mind to elaborate them?

**Comment by jdleesmiller** [comment]
I think they were internal CI issues; #23 is now up.

**Comment by mserranom** [comment]
JS code moved to the wrong folder, like in `app/js/coffee/ASpellWorker.js`. Given that the git changelog is generated automatically using the `decaffeinate.sh` script, trying to fix the PR is just too complex compared to open a new one. Closed in favour of https://github.com/overleaf/spelling/pull/23

**Comment by das7pad** [comment]
Thanks for the response!

**Pull request closed without merging**
